# Generated by Django 4.2.4 on 2023-09-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default.jpg', upload_to='products/', verbose_name='Image'),
        ),
    ]
